---
- name: install the packages.
  apt:
    pkg:
     - default-jre
    update_cache: yes

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add the transport-https-package.
  apt:
    name: apt-transport-https
    update_cache: yes

- name: Add specified repository into sources list
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
    state: present

- name: Install the elastic search over the cluster.
  apt:
    name: elasticsearch
    update_cache: yes

- name: copy the elasticsearch file to server.
  copy:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: 0644
    owner: root
    group: root


- name: restart the elasticsearch service.
  service:
    name: elasticsearch
    state: restarted
    enabled: yes 
