---
- name: install java for the elasticsearch purpose.
  apt:
    name: "{{ java_package}}" 
    state: latest
    update_cache: yes


- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: "{{ elasticsearch_key_url }}" 
    state: present

- name: Add the transport-https-package.
  apt:
    name: "{{ transport_package }}" 
    update_cache: yes

- name: Add specified repository into sources list
  apt_repository:
    repo: deb "{{ elasticsearch_repo_url }}"  stable main
    state: present

- name: Install the elastic search over the cluster.
  apt:
    name: "{{ elasticsearch_package_name }}" 
    update_cache: yes

- name: copy the elasticsearch file to server.
  copy:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: 0644
    owner: root
    group: root


- name: restart the elasticsearch service.
  service:
    name: elasticsearch
    state: restarted
    enabled: yes 
